// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type AxmName struct {
	Name          string
	KeyID         string
	ClientID      string
	PrivKeyPem    []byte
	CaToken       sql.NullString
	CaValiditySec sql.NullInt32
	CaExpiryUnix  sql.NullInt32
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}
