// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package abm

import "time"

type ErrorLinksJson struct {
	// About corresponds to the JSON schema field "about".
	About *string `json:"about,omitempty"`

	// Associated corresponds to the JSON schema field "associated".
	Associated interface{} `json:"associated,omitempty"`
}

// The details about an error that returns when an API request isn’t successful.
type ErrorResponseErrorsJson struct {
	// A machine-readable code indicating the type of error. The code is a
	// hierarchical value with levels of specificity separated by a period (.). This
	// value is parseable for programmatic error handling in code.
	Code string `json:"code"`

	// A detailed explanation of the error. Don’t use this field for programmatic
	// error handling.
	Detail string `json:"detail"`

	// The unique ID of a specific instance of an error, request, and response. Use
	// this ID when providing feedback to, or debugging issues with, Apple.
	Id *string `json:"id,omitempty"`

	// Links corresponds to the JSON schema field "links".
	Links *ErrorLinksJson `json:"links,omitempty"`

	// Meta corresponds to the JSON schema field "meta".
	Meta map[string]interface{} `json:"meta,omitempty"`

	// One of two possible types of values — source.Parameter when a query parameter
	// produces the error, or source.JsonPointer when a problem with the entity
	// produces the error.
	Source interface{} `json:"source,omitempty"`

	// The HTTP status code of the error. This status code usually matches the
	// response’s status code. However, if the request produces multiple errors, these
	// two codes may differ.
	Status string `json:"status"`

	// A summary of the error. Don’t use this field for programmatic error handling.
	Title string `json:"title"`
}

// A response that contains a list of device management service resources.
type ErrorResponseJson struct {
	// An array of one or more errors.
	Errors []ErrorResponseErrorsJson `json:"errors,omitempty"`
}

// A response that contains a list of device management service resources.
type JsonPointerJson struct {
	// A JSON pointer that indicates the location of the error in the request entity.
	Pointer string `json:"pointer"`
}

// Attributes that describe a device management service resource.
type MdmServerAttributesJson struct {
	// The date and time of the creation of the resource.
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`

	// The device management service’s name.
	ServerName *string `json:"serverName,omitempty"`

	// The type of device management service: MDM, APPLE_CONFIGURATOR, APPLE_MDM
	ServerType *MdmServerAttributesJsonServerType `json:"serverType,omitempty"`

	// The date and time of the most-recent update for the resource.
	UpdatedDateTime *time.Time `json:"updatedDateTime,omitempty"`
}

type MdmServerAttributesJsonServerType string

const MdmServerAttributesJsonServerTypeAPPLECONFIGURATOR MdmServerAttributesJsonServerType = "APPLE_CONFIGURATOR"
const MdmServerAttributesJsonServerTypeAPPLEMDM MdmServerAttributesJsonServerType = "APPLE_MDM"
const MdmServerAttributesJsonServerTypeMDM MdmServerAttributesJsonServerType = "MDM"

// The data structure that represents a device management service resource in an
// organization.
type MdmServerJson struct {
	// The resource’s attributes.
	Attributes *MdmServerAttributesJson `json:"attributes,omitempty"`

	// The opaque resource ID that uniquely identifies the resource.
	Id string `json:"id"`

	// Navigational links to related data and included resource types and IDs.
	Relationships *MdmServerRelationshipsJson `json:"relationships,omitempty"`

	// The resource type.
	Type string `json:"type"`
}

// The type and ID of a related resource.
type MdmServerRelationshipsDevicesDataJson struct {
	// The opaque resource ID that uniquely identifies the resource.
	Id string `json:"id"`

	// The resource type.
	Type interface{} `json:"type"`
}

// The data and links that describe the relationship between the resources.
type MdmServerRelationshipsDevicesJson struct {
	// Data corresponds to the JSON schema field "data".
	Data []MdmServerRelationshipsDevicesDataJson `json:"data,omitempty"`

	// Links corresponds to the JSON schema field "links".
	Links *RelationshipLinksJson `json:"links,omitempty"`

	// Meta corresponds to the JSON schema field "meta".
	Meta *PagingInformationJson `json:"meta,omitempty"`
}

// The relationships you include in the request, and those that you can operate on.
type MdmServerRelationshipsJson struct {
	// The devices in the device management service.
	Devices *MdmServerRelationshipsDevicesJson `json:"devices,omitempty"`
}

// A response that contains a list of device management service resources.
type MdmServersResponseJson struct {
	// The resource data.
	Data []MdmServerJson `json:"data"`

	// Included corresponds to the JSON schema field "included".
	Included []OrgDeviceJson `json:"included,omitempty"`

	// Navigational links that include the self-link.
	Links PagedDocumentLinksJson `json:"links"`

	// Paging information.
	Meta *PagingInformationJson `json:"meta,omitempty"`
}

// Attributes that describe an organization device resource.
type OrgDeviceAttributesJson struct {
	// The date and time of adding the device to an organization.
	AddedToOrgDateTime *time.Time `json:"addedToOrgDateTime,omitempty"`

	// The device’s Bluetooth MAC address.
	BluetoothMacAddress *string `json:"bluetoothMacAddress,omitempty"`

	// The color of the device.
	Color *string `json:"color,omitempty"`

	// The capacity of the device.
	DeviceCapacity *string `json:"deviceCapacity,omitempty"`

	// The model name.
	DeviceModel *string `json:"deviceModel,omitempty"`

	// The device’s EID (if available).
	Eid *string `json:"eid,omitempty"`

	// The device’s IMEI (if available).
	Imei *string `json:"imei,omitempty"`

	// The device’s MEID (if available).
	Meid *string `json:"meid,omitempty"`

	// The date and time of placing the device’s order.
	OrderDateTime *time.Time `json:"orderDateTime,omitempty"`

	// The order number of the device.
	OrderNumber *string `json:"orderNumber,omitempty"`

	// The part number of the device.
	PartNumber *string `json:"partNumber,omitempty"`

	// The device’s Apple product family: iPhone, iPad,Mac, AppleTV, Watch, or Vision
	ProductFamily *OrgDeviceAttributesJsonProductFamily `json:"productFamily,omitempty"`

	// The device’s product type: (examples: iPhone14,3, iPad13,4, MacBookPro14,2)
	ProductType *string `json:"productType,omitempty"`

	// The unique ID of the purchase source type: Apple Customer Number or Reseller
	// Number
	PurchaseSourceId *string `json:"purchaseSourceId,omitempty"`

	// The device’s purchase source type: APPLE, RESELLER, or MANUALLY_ADDED
	PurchaseSourceType *OrgDeviceAttributesJsonPurchaseSourceType `json:"purchaseSourceType,omitempty"`

	// The device’s serial number.
	SerialNumber *string `json:"serialNumber,omitempty"`

	// The devices status: ASSIGNED or UNASSIGNED. If ASSIGNED, use a separate API to
	// get the information of the assigned server.
	Status *OrgDeviceAttributesJsonStatus `json:"status,omitempty"`

	// The date and time of the most-recent update for the device.
	UpdatedDateTime *time.Time `json:"updatedDateTime,omitempty"`

	// The device’s Wi-Fi MAC address.
	WifiMacAddress *string `json:"wifiMacAddress,omitempty"`
}

type OrgDeviceAttributesJsonProductFamily string

const OrgDeviceAttributesJsonProductFamilyAppleTV OrgDeviceAttributesJsonProductFamily = "AppleTV"
const OrgDeviceAttributesJsonProductFamilyIPad OrgDeviceAttributesJsonProductFamily = "iPad"
const OrgDeviceAttributesJsonProductFamilyIPhone OrgDeviceAttributesJsonProductFamily = "iPhone"
const OrgDeviceAttributesJsonProductFamilyMac OrgDeviceAttributesJsonProductFamily = "Mac"
const OrgDeviceAttributesJsonProductFamilyVision OrgDeviceAttributesJsonProductFamily = "Vision"
const OrgDeviceAttributesJsonProductFamilyWatch OrgDeviceAttributesJsonProductFamily = "Watch"

type OrgDeviceAttributesJsonPurchaseSourceType string

const OrgDeviceAttributesJsonPurchaseSourceTypeAPPLE OrgDeviceAttributesJsonPurchaseSourceType = "APPLE"
const OrgDeviceAttributesJsonPurchaseSourceTypeMANUALLYADDED OrgDeviceAttributesJsonPurchaseSourceType = "MANUALLY_ADDED"
const OrgDeviceAttributesJsonPurchaseSourceTypeRESELLER OrgDeviceAttributesJsonPurchaseSourceType = "RESELLER"

type OrgDeviceAttributesJsonStatus string

const OrgDeviceAttributesJsonStatusASSIGNED OrgDeviceAttributesJsonStatus = "ASSIGNED"
const OrgDeviceAttributesJsonStatusUNASSIGNED OrgDeviceAttributesJsonStatus = "UNASSIGNED"

// The data structure that represents an organization device resource.
type OrgDeviceJson struct {
	// The resource’s attributes.
	Attributes *OrgDeviceAttributesJson `json:"attributes,omitempty"`

	// The opaque resource ID that uniquely identifies the resource.
	Id string `json:"id"`

	// Navigational links that include the self-link.
	Links *ResourceLinksJson `json:"links,omitempty"`

	// Navigational links to related data and included resource types and IDs.
	Relationships *OrgDeviceRelationshipsJson `json:"relationships,omitempty"`

	// The resource type.
	Type string `json:"type"`
}

// The links that describe the relationship between the resources.
type OrgDeviceRelationshipsAssignedServerJson struct {
	// Links corresponds to the JSON schema field "links".
	Links *RelationshipLinksJson `json:"links,omitempty"`
}

// The relationships you include in the request, and those that you can operate on.
type OrgDeviceRelationshipsJson struct {
	// The relationship representing a device and its assigned device management
	// service.
	AssignedServer *OrgDeviceRelationshipsAssignedServerJson `json:"assignedServer,omitempty"`
}

// Links related to the response document, including paging links.
type PagedDocumentLinksJson struct {
	// The link to the first page of documents.
	First *string `json:"first,omitempty"`

	// The link to the next page of documents.
	Next *string `json:"next,omitempty"`

	// The link that produces the current document.
	Self string `json:"self"`
}

// Paging information for data responses.
type PagingInformationJson struct {
	// The paging information details.
	Paging PagingInformationPagingJson `json:"paging"`
}

// Paging details, such as the total number of resources and the per-page limit.
type PagingInformationPagingJson struct {
	// The maximum number of resources to return per page.
	Limit int `json:"limit"`

	// The cursor to use for the next request, in case of pagination.
	NextCursor *string `json:"nextCursor,omitempty"`

	// The total number of resources to return.
	Total *int `json:"total,omitempty"`
}

// An object that contains the query parameter that produces the error.
type ParameterJson struct {
	// The query parameter that produces the error.
	Parameter string `json:"parameter"`
}

// Links related to the response document, including self-links.
type RelationshipLinksJson struct {
	// Include corresponds to the JSON schema field "include".
	Include *string `json:"include,omitempty"`

	// The link to the related documents.
	Related *string `json:"related,omitempty"`

	// The link that produces the current document.
	Self *string `json:"self,omitempty"`
}

// Self-links to requested resources.
type ResourceLinksJson struct {
	// The link to the resource.
	Self *string `json:"self,omitempty"`
}
