// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package abm

import "time"

// Self-links to documents that can contain information for one or more resources.
type DocumentLinksJson struct {
	// The link that produces the current
	Self string `json:"self"`
}

type ErrorLinksJson struct {
	// About corresponds to the JSON schema field "about".
	About *string `json:"about,omitempty"`

	// Associated corresponds to the JSON schema field "associated".
	Associated interface{} `json:"associated,omitempty"`
}

// The details about an error that returns when an API request isn’t successful.
type ErrorResponseErrorsJson struct {
	// A machine-readable code indicating the type of error. The code is a
	// hierarchical value with levels of specificity separated by a period (.). This
	// value is parseable for programmatic error handling in code.
	Code string `json:"code"`

	// A detailed explanation of the error. Don’t use this field for programmatic
	// error handling.
	Detail string `json:"detail"`

	// The unique ID of a specific instance of an error, request, and response. Use
	// this ID when providing feedback to, or debugging issues with, Apple.
	Id *string `json:"id,omitempty"`

	// Links corresponds to the JSON schema field "links".
	Links *ErrorLinksJson `json:"links,omitempty"`

	// Meta corresponds to the JSON schema field "meta".
	Meta map[string]interface{} `json:"meta,omitempty"`

	// One of two possible types of values — source.Parameter when a query parameter
	// produces the error, or source.JsonPointer when a problem with the entity
	// produces the error.
	Source interface{} `json:"source,omitempty"`

	// The HTTP status code of the error. This status code usually matches the
	// response’s status code. However, if the request produces multiple errors, these
	// two codes may differ.
	Status string `json:"status"`

	// A summary of the error. Don’t use this field for programmatic error handling.
	Title string `json:"title"`
}

// The error details that an API returns in the response body whenever the API
// request isn’t successful.
type ErrorResponseJson struct {
	// An array of one or more errors.
	Errors []ErrorResponseErrorsJson `json:"errors,omitempty"`
}

// Attributes that describe a device management service resource.
type MdmServerAttributesJson struct {
	// The date and time of the creation of the resource.
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`

	// The device management service’s name.
	ServerName *string `json:"serverName,omitempty"`

	// The type of device management service: MDM, APPLE_CONFIGURATOR, APPLE_MDM
	ServerType *MdmServerAttributesJsonServerType `json:"serverType,omitempty"`

	// The date and time of the most-recent update for the resource.
	UpdatedDateTime *time.Time `json:"updatedDateTime,omitempty"`
}

type MdmServerAttributesJsonServerType string

const MdmServerAttributesJsonServerTypeAPPLECONFIGURATOR MdmServerAttributesJsonServerType = "APPLE_CONFIGURATOR"
const MdmServerAttributesJsonServerTypeAPPLEMDM MdmServerAttributesJsonServerType = "APPLE_MDM"
const MdmServerAttributesJsonServerTypeMDM MdmServerAttributesJsonServerType = "MDM"

// The data structure that represents a device management service resource in an
// organization.
type MdmServerJson struct {
	// The resource’s attributes.
	Attributes *MdmServerAttributesJson `json:"attributes,omitempty"`

	// The opaque resource ID that uniquely identifies the resource.
	Id string `json:"id"`

	// Navigational links to related data and included resource types and IDs.
	Relationships *MdmServerRelationshipsJson `json:"relationships,omitempty"`

	// The resource type.
	Type string `json:"type"`
}

// The type and ID of a related resource.
type MdmServerRelationshipsDevicesDataJson struct {
	// The opaque resource ID that uniquely identifies the resource.
	Id string `json:"id"`

	// The resource type.
	Type interface{} `json:"type"`
}

// The data and links that describe the relationship between the resources.
type MdmServerRelationshipsDevicesJson struct {
	// Data corresponds to the JSON schema field "data".
	Data []MdmServerRelationshipsDevicesDataJson `json:"data,omitempty"`

	// Links corresponds to the JSON schema field "links".
	Links *RelationshipLinksJson `json:"links,omitempty"`

	// Meta corresponds to the JSON schema field "meta".
	Meta *PagingInformationJson `json:"meta,omitempty"`
}

// The relationships you include in the request, and those that you can operate on.
type MdmServerRelationshipsJson struct {
	// The devices in the device management service.
	Devices *MdmServerRelationshipsDevicesJson `json:"devices,omitempty"`
}

// A response that contains a list of device management service resources.
type MdmServersResponseJson struct {
	// The resource data.
	Data []MdmServerJson `json:"data"`

	// Included corresponds to the JSON schema field "included".
	Included []OrgDeviceJson `json:"included,omitempty"`

	// Navigational links that include the self-link.
	Links PagedDocumentLinksJson `json:"links"`

	// Paging information.
	Meta *PagingInformationJson `json:"meta,omitempty"`
}

// Attributes that describe an organization device activity resource.
type OrgDeviceActivityAttributesJson struct {
	// The date and time of the completion of organization device activity. This is
	// available only when an activity is in a COMPLETED status.
	CompletedDateTime *time.Time `json:"completedDateTime,omitempty"`

	// The date and time of the creation of organization device activity.
	CreatedDateTime *time.Time `json:"createdDateTime,omitempty"`

	// A presigned URL for downloading activity logs in a CSV format. This is
	// available only when an activity is in a COMPLETED status.
	DownloadUrl *string `json:"downloadUrl,omitempty"`

	// The top-level status of an activity. For more details, see the table below.
	// Possible values: COMPLETED, IN_PROGRESS, STOPPED, FAILED
	Status *OrgDeviceActivityAttributesJsonStatus `json:"status,omitempty"`

	// The low-level status of an activity. For more details, see the table below.
	// Possible values: SUBMITTED,PRE_PROCESSING,PENDING,PROCESSING,POST_PROCESSING,
	// STOPPING,COMPLETED_WITH_SUCCESS,COMPLETED_WITH_ERROR,COMPLETED_WITH_FAILURE,COMPLETED_POST_PROCESSING_FAILED
	SubStatus *OrgDeviceActivityAttributesJsonSubStatus `json:"subStatus,omitempty"`
}

type OrgDeviceActivityAttributesJsonStatus string

const OrgDeviceActivityAttributesJsonStatusCOMPLETED OrgDeviceActivityAttributesJsonStatus = "COMPLETED"
const OrgDeviceActivityAttributesJsonStatusFAILED OrgDeviceActivityAttributesJsonStatus = "FAILED"
const OrgDeviceActivityAttributesJsonStatusINPROGRESS OrgDeviceActivityAttributesJsonStatus = "IN_PROGRESS"
const OrgDeviceActivityAttributesJsonStatusSTOPPED OrgDeviceActivityAttributesJsonStatus = "STOPPED"

type OrgDeviceActivityAttributesJsonSubStatus string

const OrgDeviceActivityAttributesJsonSubStatusCOMPLETEDPOSTPROCESSINGFAILED OrgDeviceActivityAttributesJsonSubStatus = "COMPLETED_POST_PROCESSING_FAILED"
const OrgDeviceActivityAttributesJsonSubStatusCOMPLETEDWITHERROR OrgDeviceActivityAttributesJsonSubStatus = "COMPLETED_WITH_ERROR"
const OrgDeviceActivityAttributesJsonSubStatusCOMPLETEDWITHFAILURE OrgDeviceActivityAttributesJsonSubStatus = "COMPLETED_WITH_FAILURE"
const OrgDeviceActivityAttributesJsonSubStatusCOMPLETEDWITHSUCCESS OrgDeviceActivityAttributesJsonSubStatus = "COMPLETED_WITH_SUCCESS"
const OrgDeviceActivityAttributesJsonSubStatusPENDING OrgDeviceActivityAttributesJsonSubStatus = "PENDING"
const OrgDeviceActivityAttributesJsonSubStatusPOSTPROCESSING OrgDeviceActivityAttributesJsonSubStatus = "POST_PROCESSING"
const OrgDeviceActivityAttributesJsonSubStatusPREPROCESSING OrgDeviceActivityAttributesJsonSubStatus = "PRE_PROCESSING"
const OrgDeviceActivityAttributesJsonSubStatusPROCESSING OrgDeviceActivityAttributesJsonSubStatus = "PROCESSING"
const OrgDeviceActivityAttributesJsonSubStatusSTOPPING OrgDeviceActivityAttributesJsonSubStatus = "STOPPING"
const OrgDeviceActivityAttributesJsonSubStatusSUBMITTED OrgDeviceActivityAttributesJsonSubStatus = "SUBMITTED"

// Attributes with values that you’re changing as part of the create request.
type OrgDeviceActivityCreateRequestDataAttributesJson struct {
	// The type of activity you want to create.
	ActivityType OrgDeviceActivityTypeJson `json:"activityType"`
}

// The request body you use to update the device management service for a device.
type OrgDeviceActivityCreateRequestDataJson struct {
	// The resource’s attributes.
	Attributes OrgDeviceActivityCreateRequestDataAttributesJson `json:"attributes"`

	// The types and IDs of the related data to update.
	Relationships OrgDeviceActivityCreateRequestDataRelationshipsJson `json:"relationships"`

	// The resource type.
	Type string `json:"type"`
}

// The type and ID of a related resource.
type OrgDeviceActivityCreateRequestDataRelationshipsDevicesDataJson struct {
	// The opaque resource ID that uniquely identifies the resource.
	Id string `json:"id"`

	// The resource type.
	Type string `json:"type"`
}

// The data that describe the relationship between the resources.
type OrgDeviceActivityCreateRequestDataRelationshipsDevicesJson struct {
	// Data corresponds to the JSON schema field "data".
	Data []OrgDeviceActivityCreateRequestDataRelationshipsDevicesDataJson `json:"data"`
}

// The relationships you include in the request, and those that you can operate on.
type OrgDeviceActivityCreateRequestDataRelationshipsJson struct {
	// Devices corresponds to the JSON schema field "devices".
	Devices OrgDeviceActivityCreateRequestDataRelationshipsDevicesJson `json:"devices"`

	// MdmServer corresponds to the JSON schema field "mdmServer".
	MdmServer *OrgDeviceActivityCreateRequestDataRelationshipsMdmServerJson `json:"mdmServer,omitempty"`
}

// The type and ID of a related resource.
type OrgDeviceActivityCreateRequestDataRelationshipsMdmServerDataJson struct {
	// The opaque resource ID that uniquely identifies the resource.
	Id string `json:"id"`

	// The resource type.
	Type string `json:"type"`
}

// The data that describe the relationship between the resources.
type OrgDeviceActivityCreateRequestDataRelationshipsMdmServerJson struct {
	// Data corresponds to the JSON schema field "data".
	Data OrgDeviceActivityCreateRequestDataRelationshipsMdmServerDataJson `json:"data"`
}

// The request body you use to update the device management service for a device.
type OrgDeviceActivityCreateRequestJson struct {
	// The resource data.
	Data OrgDeviceActivityCreateRequestDataJson `json:"data"`
}

// The data structure that represents an organization device activity resource.
type OrgDeviceActivityJson struct {
	// The resource’s attributes.
	Attributes *OrgDeviceActivityAttributesJson `json:"attributes,omitempty"`

	// The opaque resource ID that uniquely identifies the resource.
	Id string `json:"id"`

	// Navigational links that include the self-link.
	Links *ResourceLinksJson `json:"links,omitempty"`

	// The resource type.
	Type string `json:"type"`
}

// A response that contains a single organization device activity resource.
type OrgDeviceActivityResponseJson struct {
	// The resource data.
	Data OrgDeviceActivityJson `json:"data"`

	// Navigational links that include the self-link.
	Links DocumentLinksJson `json:"links"`
}

// Strings that represent organization device activities.
type OrgDeviceActivityTypeJson string

// Attributes that describe an organization device resource.
type OrgDeviceAttributesJson struct {
	// The date and time of adding the device to an organization.
	AddedToOrgDateTime *time.Time `json:"addedToOrgDateTime,omitempty"`

	// The device’s Bluetooth MAC address.
	BluetoothMacAddress *string `json:"bluetoothMacAddress,omitempty"`

	// The color of the device.
	Color *string `json:"color,omitempty"`

	// The capacity of the device.
	DeviceCapacity *string `json:"deviceCapacity,omitempty"`

	// The model name.
	DeviceModel *string `json:"deviceModel,omitempty"`

	// The device’s EID (if available).
	Eid *string `json:"eid,omitempty"`

	// The device’s IMEI (if available).
	Imei *string `json:"imei,omitempty"`

	// The device’s MEID (if available).
	Meid *string `json:"meid,omitempty"`

	// The date and time of placing the device’s order.
	OrderDateTime *time.Time `json:"orderDateTime,omitempty"`

	// The order number of the device.
	OrderNumber *string `json:"orderNumber,omitempty"`

	// The part number of the device.
	PartNumber *string `json:"partNumber,omitempty"`

	// The device’s Apple product family: iPhone, iPad,Mac, AppleTV, Watch, or Vision
	ProductFamily *OrgDeviceAttributesJsonProductFamily `json:"productFamily,omitempty"`

	// The device’s product type: (examples: iPhone14,3, iPad13,4, MacBookPro14,2)
	ProductType *string `json:"productType,omitempty"`

	// The unique ID of the purchase source type: Apple Customer Number or Reseller
	// Number
	PurchaseSourceId *string `json:"purchaseSourceId,omitempty"`

	// The device’s purchase source type: APPLE, RESELLER, or MANUALLY_ADDED
	PurchaseSourceType *OrgDeviceAttributesJsonPurchaseSourceType `json:"purchaseSourceType,omitempty"`

	// The device’s serial number.
	SerialNumber *string `json:"serialNumber,omitempty"`

	// The devices status: ASSIGNED or UNASSIGNED. If ASSIGNED, use a separate API to
	// get the information of the assigned server.
	Status *OrgDeviceAttributesJsonStatus `json:"status,omitempty"`

	// The date and time of the most-recent update for the device.
	UpdatedDateTime *time.Time `json:"updatedDateTime,omitempty"`

	// The device’s Wi-Fi MAC address.
	WifiMacAddress *string `json:"wifiMacAddress,omitempty"`
}

type OrgDeviceAttributesJsonProductFamily string

const OrgDeviceAttributesJsonProductFamilyAppleTV OrgDeviceAttributesJsonProductFamily = "AppleTV"
const OrgDeviceAttributesJsonProductFamilyIPad OrgDeviceAttributesJsonProductFamily = "iPad"
const OrgDeviceAttributesJsonProductFamilyIPhone OrgDeviceAttributesJsonProductFamily = "iPhone"
const OrgDeviceAttributesJsonProductFamilyMac OrgDeviceAttributesJsonProductFamily = "Mac"
const OrgDeviceAttributesJsonProductFamilyVision OrgDeviceAttributesJsonProductFamily = "Vision"
const OrgDeviceAttributesJsonProductFamilyWatch OrgDeviceAttributesJsonProductFamily = "Watch"

type OrgDeviceAttributesJsonPurchaseSourceType string

const OrgDeviceAttributesJsonPurchaseSourceTypeAPPLE OrgDeviceAttributesJsonPurchaseSourceType = "APPLE"
const OrgDeviceAttributesJsonPurchaseSourceTypeMANUALLYADDED OrgDeviceAttributesJsonPurchaseSourceType = "MANUALLY_ADDED"
const OrgDeviceAttributesJsonPurchaseSourceTypeRESELLER OrgDeviceAttributesJsonPurchaseSourceType = "RESELLER"

type OrgDeviceAttributesJsonStatus string

const OrgDeviceAttributesJsonStatusASSIGNED OrgDeviceAttributesJsonStatus = "ASSIGNED"
const OrgDeviceAttributesJsonStatusUNASSIGNED OrgDeviceAttributesJsonStatus = "UNASSIGNED"

// The data structure that represents an organization device resource.
type OrgDeviceJson struct {
	// The resource’s attributes.
	Attributes *OrgDeviceAttributesJson `json:"attributes,omitempty"`

	// The opaque resource ID that uniquely identifies the resource.
	Id string `json:"id"`

	// Navigational links that include the self-link.
	Links *ResourceLinksJson `json:"links,omitempty"`

	// Navigational links to related data and included resource types and IDs.
	Relationships *OrgDeviceRelationshipsJson `json:"relationships,omitempty"`

	// The resource type.
	Type string `json:"type"`
}

// The links that describe the relationship between the resources.
type OrgDeviceRelationshipsAssignedServerJson struct {
	// Links corresponds to the JSON schema field "links".
	Links *RelationshipLinksJson `json:"links,omitempty"`
}

// The relationships you include in the request, and those that you can operate on.
type OrgDeviceRelationshipsJson struct {
	// The relationship representing a device and its assigned device management
	// service.
	AssignedServer *OrgDeviceRelationshipsAssignedServerJson `json:"assignedServer,omitempty"`
}

// Links related to the response document, including paging links.
type PagedDocumentLinksJson struct {
	// The link to the first page of documents.
	First *string `json:"first,omitempty"`

	// The link to the next page of documents.
	Next *string `json:"next,omitempty"`

	// The link that produces the current document.
	Self string `json:"self"`
}

// Paging information for data responses.
type PagingInformationJson struct {
	// The paging information details.
	Paging PagingInformationPagingJson `json:"paging"`
}

// Paging details, such as the total number of resources and the per-page limit.
type PagingInformationPagingJson struct {
	// The maximum number of resources to return per page.
	Limit int `json:"limit"`

	// The cursor to use for the next request, in case of pagination.
	NextCursor *string `json:"nextCursor,omitempty"`

	// The total number of resources to return.
	Total *int `json:"total,omitempty"`
}

// Links related to the response document, including self-links.
type RelationshipLinksJson struct {
	// Include corresponds to the JSON schema field "include".
	Include *string `json:"include,omitempty"`

	// The link to the related documents.
	Related *string `json:"related,omitempty"`

	// The link that produces the current document.
	Self *string `json:"self,omitempty"`
}

// Self-links to requested resources.
type ResourceLinksJson struct {
	// The link to the resource.
	Self *string `json:"self,omitempty"`
}
